// Maps the estate palette onto Backstage UI's CSS variables. BUI reads these; the hex
// values still live only in tokens.ts. Official names: https://ui.backstage.io/tokens
import type { CSSProperties } from 'react';
import {
  Tone,
  StateTint,
  fontFamily,
  monoFamily,
} from './tokens';

export function buiVars(
  tone: Tone,
  status: Record<'red' | 'needs' | 'running' | 'good', StateTint>,
): CSSProperties {
  return {
    '--bui-black': '#000000',
    '--bui-white': '#ffffff',
    '--bui-bg-app': tone.canvas,
    '--bui-bg-neutral-1': tone.surface1,
    '--bui-bg-neutral-1-hover': tone.surface2,
    '--bui-bg-neutral-1-pressed': tone.surface3,
    '--bui-bg-neutral-1-disabled': tone.surface1,
    '--bui-bg-neutral-2': tone.surface2,
    '--bui-bg-neutral-2-hover': tone.surface3,
    '--bui-bg-neutral-2-pressed': tone.surface3,
    '--bui-bg-neutral-2-disabled': tone.surface2,
    '--bui-bg-neutral-3': tone.surface3,
    '--bui-bg-neutral-3-hover': tone.surface3,
    '--bui-bg-neutral-3-pressed': tone.surface3,
    '--bui-bg-neutral-3-disabled': tone.surface3,
    '--bui-bg-neutral-4': tone.surface3,
    '--bui-bg-neutral-4-hover': tone.surface3,
    '--bui-bg-neutral-4-pressed': tone.surface3,
    '--bui-bg-neutral-4-disabled': tone.surface3,
    // 0.16+ semantic families. Primary buttons read --bui-accent-*, not --bui-bg-solid.
    // https://ui.backstage.io/changelog
    '--bui-accent-bg': tone.accent,
    '--bui-accent-bg-hover': tone.accentPressed,
    '--bui-accent-bg-disabled': tone.border,
    '--bui-accent-fg': tone.inkOnAccent,
    '--bui-accent-fg-disabled': tone.textMuted,
    '--bui-negative-bg': status.red.ink,
    '--bui-negative-bg-hover': status.red.edge,
    '--bui-negative-bg-disabled': status.red.bg,
    '--bui-negative-bg-subdued': status.red.bg,
    '--bui-negative-bg-subdued-hover': status.red.bg,
    '--bui-negative-bg-subdued-disabled': status.red.bg,
    '--bui-negative-border': status.red.edge,
    '--bui-negative-fg': tone.inkOnAccent,
    '--bui-negative-fg-disabled': tone.textMuted,
    '--bui-negative-fg-subdued': status.red.ink,
    '--bui-negative-fg-subdued-disabled': tone.textMuted,
    '--bui-warning-bg': status.needs.ink,
    '--bui-warning-bg-hover': status.needs.edge,
    '--bui-warning-bg-disabled': status.needs.bg,
    '--bui-warning-bg-subdued': status.needs.bg,
    '--bui-warning-bg-subdued-hover': status.needs.bg,
    '--bui-warning-bg-subdued-disabled': status.needs.bg,
    '--bui-warning-border': status.needs.edge,
    '--bui-warning-fg': tone.inkOnAccent,
    '--bui-warning-fg-disabled': tone.textMuted,
    '--bui-warning-fg-subdued': status.needs.ink,
    '--bui-warning-fg-subdued-disabled': tone.textMuted,
    '--bui-positive-bg': status.good.ink,
    '--bui-positive-bg-hover': status.good.edge,
    '--bui-positive-bg-disabled': status.good.bg,
    '--bui-positive-bg-subdued': status.good.bg,
    '--bui-positive-bg-subdued-hover': status.good.bg,
    '--bui-positive-bg-subdued-disabled': status.good.bg,
    '--bui-positive-border': status.good.edge,
    '--bui-positive-fg': tone.inkOnAccent,
    '--bui-positive-fg-disabled': tone.textMuted,
    '--bui-positive-fg-subdued': status.good.ink,
    '--bui-positive-fg-subdued-disabled': tone.textMuted,
    '--bui-announcement-bg': status.running.ink,
    '--bui-announcement-bg-hover': status.running.edge,
    '--bui-announcement-bg-disabled': status.running.bg,
    '--bui-announcement-bg-subdued': status.running.bg,
    '--bui-announcement-bg-subdued-hover': status.running.bg,
    '--bui-announcement-bg-subdued-disabled': status.running.bg,
    '--bui-announcement-border': status.running.edge,
    '--bui-announcement-fg': tone.inkOnAccent,
    '--bui-announcement-fg-disabled': tone.textMuted,
    '--bui-announcement-fg-subdued': status.running.ink,
    '--bui-announcement-fg-subdued-disabled': tone.textMuted,
    // Legacy names still present in 0.17.1 CSS. Keep them on the same palette.
    '--bui-bg-solid': tone.accent,
    '--bui-bg-solid-hover': tone.accentPressed,
    '--bui-bg-solid-pressed': tone.accentPressed,
    '--bui-bg-solid-disabled': tone.border,
    '--bui-bg-danger': status.red.bg,
    '--bui-bg-warning': status.needs.bg,
    '--bui-bg-success': status.good.bg,
    '--bui-bg-info': status.running.bg,
    '--bui-fg-primary': tone.textPrimary,
    '--bui-fg-secondary': tone.textSecondary,
    '--bui-fg-disabled': tone.textMuted,
    '--bui-fg-solid': tone.inkOnAccent,
    '--bui-fg-danger': status.red.ink,
    '--bui-fg-warning': status.needs.ink,
    '--bui-fg-success': status.good.ink,
    '--bui-fg-info': status.running.ink,
    '--bui-fg-negative': status.red.ink,
    '--bui-fg-positive': status.good.ink,
    '--bui-fg-announcement': status.running.ink,
    '--bui-fg-danger-on-bg': status.red.ink,
    '--bui-fg-warning-on-bg': status.needs.ink,
    '--bui-fg-success-on-bg': status.good.ink,
    '--bui-fg-info-on-bg': status.running.ink,
    '--bui-border-1': tone.borderSubtle,
    '--bui-border-2': tone.border,
    '--bui-border-danger': status.red.edge,
    '--bui-border-warning': status.needs.edge,
    '--bui-border-success': status.good.edge,
    '--bui-border-info': status.running.edge,
    '--bui-ring': tone.accent,
    '--bui-scrollbar': tone.borderSubtle,
    '--bui-scrollbar-thumb': tone.borderStrong,
    '--bui-font-regular': fontFamily,
    '--bui-font-monospace': monoFamily,
    // Slightly rounder than the BUI defaults so cards read as 2026, not 2020.
    '--bui-radius-3': '0.75rem',
    '--bui-radius-4': '1rem',
    '--bui-radius-5': '1.25rem',
  } as CSSProperties;
}
