"""2026-08-30: `bin/idp-kyverno-render platform/tailscale` printed `ok render tailscale-operator
... pass: 35, fail: 0` while the cluster refused the very same object. Break-glass diagnose run
33335791923 printed the denial:

    resource Pod/tailscale/operator-56cf79864d-hjdcg was blocked due to the following policies
    require-pod-probes:
      validate-probes: 'validation failure: Liveness, readiness, or startup probes are required'

tailscale was down, and Guacamole and Temporal were down behind it on a Flux dependency.

Kyverno judges a Deployment with the AUTOGENERATED copy of a rule and the Pod its ReplicaSet then
creates with the ORIGINAL. The exception excusing the workload named `autogen-validate-probes` and
not `validate-probes`, so the Deployment was excused and the Pod was not. Offline, only the
Deployment was ever handed to the CLI -- so the judge graded the one surface that was excused.

Class on the estate ledger: fix-proved-on-the-wrong-surface (3 occurrences before this one). The
other half was already known -- crew#284 found autogen does not cover Job or CronJob and the Pod
was synthesised for those two kinds. Autogen covering a kind is exactly what made the other three
look safe: it covers the policy, never the exception.

These tests do not re-render anything; the render itself is proved by the kyverno rung in
bin/idp-ci. They hold the property that made the render lie."""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "bin" / "lib"))

from kyverno_pods import pods_for  # noqa: E402

RENDER = (ROOT / "bin" / "idp-kyverno-render").read_text()


def _workload(kind, name="operator", ns="tailscale"):
    tpl = {
        "metadata": {"labels": {"app": name}},
        "spec": {"containers": [{"name": "c", "image": "i"}]},
    }
    spec = (
        {"jobTemplate": {"spec": {"template": tpl}}}
        if kind == "CronJob"
        else {"template": tpl}
    )
    return {
        "apiVersion": "apps/v1",
        "kind": kind,
        "metadata": {"name": name, "namespace": ns},
        "spec": spec,
    }


def test_every_controller_that_makes_pods_gets_its_pod_judged():
    """The regression itself: a Deployment produced no Pod for the judge, so the rule that fires
    at admission was never run offline."""
    for kind in ("Deployment", "StatefulSet", "DaemonSet", "Job", "CronJob"):
        pods = pods_for([_workload(kind)])
        assert len(pods) == 1, (
            f"{kind} makes pods and admission judges them; the judge saw none"
        )
        assert pods[0]["kind"] == "Pod"
        assert pods[0]["spec"]["containers"][0]["name"] == "c", (
            f"{kind} pod lost its containers"
        )
        assert pods[0]["metadata"]["namespace"] == "tailscale"


def test_a_pods_name_still_matches_the_exception_written_for_its_workload():
    """The live exception matches `names: [operator*]`, and the cluster's pod was
    `operator-56cf79864d-hjdcg`. A synthesised name that broke the prefix would make every
    workload-scoped exception look unused and turn the judge red on correct config."""
    pod = pods_for([_workload("Deployment")])[0]
    assert pod["metadata"]["name"].startswith("operator"), pod["metadata"]["name"]


def test_the_owner_chain_is_the_one_admission_sees():
    """A Deployment's Pod is owned by a ReplicaSet and a CronJob's by a Job -- neither names the
    workload. A policy or exception matching on the owner has to see the same chain."""
    assert (
        pods_for([_workload("Deployment")])[0]["metadata"]["ownerReferences"][0]["kind"]
        == "ReplicaSet"
    )
    assert (
        pods_for([_workload("CronJob")])[0]["metadata"]["ownerReferences"][0]["kind"]
        == "Job"
    )
    assert (
        pods_for([_workload("DaemonSet")])[0]["metadata"]["ownerReferences"][0]["kind"]
        == "DaemonSet"
    )


def test_objects_that_make_no_pods_are_left_alone():
    for kind in (
        "Service",
        "Ingress",
        "PersistentVolumeClaim",
        "ClusterSecretStore",
        "ConfigMap",
    ):
        assert pods_for([{"kind": kind, "metadata": {"name": "x"}, "spec": {}}]) == []


def test_both_paths_through_the_judge_synthesise_the_pod():
    """A workload reaches the CLI two ways: rendered from a HelmRelease, and shipped as plain YAML
    in the directory (crew#284, the litellm Deployment). The tailscale operator came through the
    first. Fixing one and not the other leaves the same hole under the other door."""
    assert RENDER.count("from kyverno_pods import pods_for") == 2, (
        "the release path and the plain-workload path must both synthesise the pod"
    )
    assert RENDER.count("docs += pods_for(docs)") == 2


def test_the_helper_is_importable_from_a_bare_interpreter():
    """The judge adds bin/lib to sys.path and imports it with no package installed; an import that
    only works under pytest would go BLIND in CI and, before crew#539, BLIND read as a pass."""
    r = subprocess.run(
        [
            sys.executable,
            "-c",
            f"import sys; sys.path.insert(0, {str(ROOT / 'bin' / 'lib')!r}); "
            "import kyverno_pods; print(len(kyverno_pods.pods_for([])))",
        ],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert r.returncode == 0, r.stderr
    assert r.stdout.strip() == "0"
