"""crew#459 (founder, 2026-08-29): "where are all our components, tools, services?", "all the
tooling we use in our cluster is hidden away". Every Flux Kustomization under clusters/<cluster>
is a Component in backstage/platform/catalog-info.yaml, generated by bin/catalog-platform, and the
generated file is current. A layer that runs and is not in the catalogue is the incident.
"""
import glob
import os
import subprocess
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLUSTER = os.environ.get("CLUSTER", "oke")
OUT = os.path.join(ROOT, "backstage", "platform", "catalog-info.yaml")


def _kustomizations():
    names = set()
    for f in glob.glob(os.path.join(ROOT, "clusters", CLUSTER, "*.yaml")):
        for d in yaml.safe_load_all(open(f)):
            if d and d.get("kind") == "Kustomization" and str(d.get("apiVersion", "")).startswith("kustomize.toolkit"):
                names.add(d["metadata"]["name"])
    return names


def _entities():
    return [d for d in yaml.safe_load_all(open(OUT)) if d]


def test_generated_catalogue_is_current():
    r = subprocess.run([sys.executable, os.path.join(ROOT, "bin", "catalog-platform"), "--check"], capture_output=True, text=True)
    assert r.returncode == 0, r.stdout + r.stderr


def test_every_kustomization_is_a_platform_layer_component():
    comps = {e["metadata"]["annotations"]["estate/flux-kustomization"]: e for e in _entities() if e["kind"] == "Component"}
    missing = _kustomizations() - set(comps)
    assert not missing, f"layers the cluster runs with no catalogue entity: {sorted(missing)}"
    for name, e in comps.items():
        assert e["spec"]["type"] == "platform-layer", name
        assert e["metadata"]["annotations"]["backstage.io/kubernetes-label-selector"] == f"kustomize.toolkit.fluxcd.io/name={name}", name
        assert e["metadata"]["title"] and e["metadata"]["description"].endswith("."), f"{name} has no plain-English row"


def test_every_layer_has_a_system_that_exists():
    ents = _entities()
    systems = {e["metadata"]["name"] for e in ents if e["kind"] == "System"}
    for e in ents:
        if e["kind"] == "Component":
            assert e["spec"]["system"] in systems, e["metadata"]["name"]


def test_the_portal_reads_the_platform_catalogue_and_may_read_flux():
    for cfg in ("backstage/app-config.container.yaml", "backstage/app-config.yaml"):
        assert "platform/catalog-info.yaml" in open(os.path.join(ROOT, cfg)).read(), cfg
    rbac = open(os.path.join(ROOT, "platform/backstage/base/rbac.yaml")).read()
    assert "kustomize.toolkit.fluxcd.io" in rbac and "kustomizations" in rbac
    overlay = open(os.path.join(ROOT, "platform/backstage/overlays/oke/kustomization.yaml")).read()
    assert "platform-catalog" in overlay


def test_the_notify_fanout_layer_is_catalogued():
    """The 2026-09-01 release wave shipped the notification fan-out; the incident this file
    guards is a layer that runs with no catalogue row, and notify was the newest instance."""
    assert "notify" in _kustomizations(), "the notify layer is not a Flux Kustomization"
    comps = {e["metadata"]["annotations"]["estate/flux-kustomization"]: e for e in _entities() if e["kind"] == "Component"}
    e = comps.get("notify")
    assert e, "the notify layer has no catalogue entity"
    assert e["metadata"]["title"] and e["metadata"]["description"].endswith("."), "notify has no plain-English row"
