"""crew#583 CP2: `bin/estate-next` may not ask this machine what time it is.

Every handoff the page grades was stamped by some other session on some other machine, and the
page subtracted those stamps from `datetime.now()`. That is one clock minus a different clock
while reading like one, and on 2026-08-27 this estate watched it happen: a flat battery reset the
founder Mac's RTC, 1970 stamps appeared, and every age was confidently wrong. Founder,
2026-08-28: "we must eliminate absolute trust in the local machine's clock."

`bin/estate-founder` is the same class and is fixed by idp#623, which puts the served clock in
`bin/lib/receipt_age.py`; this file does not touch it.

The guard in `test_guard_freshness_is_never_measured_against_this_machines_clock.py` reads source
text and so proves only that the call is gone. These tests drive the real script: where the clock
comes from, and what it says when there is no clock to be had. All three are red against
`bin/estate-next` as it stands on origin/main.
"""
from __future__ import annotations

import importlib.machinery
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NEXT = ROOT / "bin" / "estate-next"


def _load():
    spec = importlib.util.spec_from_loader(
        "estate_next_crew583", importlib.machinery.SourceFileLoader("estate_next_crew583", str(NEXT)))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _generated_line(page: str) -> str:
    """The `GENERATED by ... at <when>` line the page stamps itself with."""
    line = next((l for l in page.splitlines() if l.startswith("GENERATED by")), None)
    assert line is not None, "the page carries no GENERATED line:\n%s" % page
    return line


FEED = """## 2026-01-02T09:00Z · aaaa · code
🔴 Blocked: nothing on the founder
🟡 Active: crew#900 CP1

## 2026-01-02T10:30Z · aaaa · code
🔴 Blocked: waiting on the vault seed
🟡 Active: crew#900 CP1
"""

ISSUES = [{"number": 900, "title": "a lane that stopped writing months ago", "url": "",
           "body": "- [ ] CP1: the thing\n      Expect: 2026-01-03\n"}]


def _render(tmp_path, feed_text):
    (tmp_path / "issues.json").write_text(json.dumps(ISSUES))
    (tmp_path / "feed.md").write_text(feed_text)
    out = tmp_path / "NEXT.md"
    r = subprocess.run([sys.executable, str(NEXT), "--issues", str(tmp_path / "issues.json"),
                        "--feed", str(tmp_path / "feed.md"), "--out", str(out)],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stdout + r.stderr
    return out.read_text()


def test_a_lane_is_live_relative_to_the_newest_handoff_not_to_today():
    """`lanes()` asks "is this lane still writing", and the reference is the last thing the estate
    wrote, not the date on the wall. A feed of January handoffs read in August is not a dead
    estate -- it is a feed that ends in January, and both handoffs here are inside the window of
    its end.

    Pre-patch this returned {} for any feed older than 3 hours, so it also returned {} on a laptop
    whose clock had jumped forward, silently dropping every 🔴 line the page exists to show.
    """
    live = _load().lanes(FEED)
    assert list(live) == ["code"], live
    assert live["code"]["at"] == "2026-01-02T10:30Z", live
    assert live["code"]["red"] == "Blocked: waiting on the vault seed", live


def test_the_page_header_is_dated_by_the_feed_it_rendered_not_by_this_machine(tmp_path):
    """The header and the ages must agree, and both must come from the same foreign clock: a page
    dated 1970 over rows aged correctly off the feed is the reset-RTC failure printing itself."""
    header = _generated_line(_render(tmp_path, FEED))
    assert "2026-01-02T10:30Z" in header, header


def test_a_feed_with_no_dated_handoff_says_so_in_the_header(tmp_path):
    """No stamp anywhere means no clock anywhere. The header says it does not know rather than
    reaching for the one clock this file is not allowed to trust."""
    header = _generated_line(_render(tmp_path, "no handoff headings here at all\n"))
    assert "an unknown time (no dated handoff in the feed)" in header, header
