"""crew#177: Healthchecks, the job monitor (STANDARDS.md row 21). Rules (rung 2, properties over the
manifests):
  1. no person holds a secret: every secret env comes from the vault (ExternalSecret), the app
     reads REMOTE_USER_HEADER from the front door and registration is closed (ADR 0007);
  2. the ping key the Mac uses and the key the server enrols are the same vault entry;
  3. the row passes the restricted profile the namespace enforces (non-root, no privilege
     escalation, read-only root, all capabilities dropped) on every container;
  4. the Flux row waits on the Deployment, after identity and secret-store, and substitutes the zone.
"""
import pathlib
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
ROW = ROOT / "platform/healthchecks"


def _docs(rel):
    return [d for d in yaml.safe_load_all((ROW / rel).read_text()) if d]


def _one(rel, kind, name):
    hits = [d for d in _docs(rel) if d.get("kind") == kind and d["metadata"]["name"] == name]
    assert len(hits) == 1, (rel, kind, name, len(hits))
    return hits[0]


def test_no_person_holds_a_secret_and_the_front_door_is_the_only_way_in():
    env = _one("env.yaml", "ConfigMap", "healthchecks-env")["data"]
    assert env["REGISTRATION_OPEN"] == "False" and env["DEBUG"] == "False"
    assert env["REMOTE_USER_HEADER"] == "HTTP_X_AUTH_REQUEST_EMAIL"
    mw = _one("httproute.yaml", "Middleware", "login-forward-auth")
    assert "X-Auth-Request-Email" in mw["spec"]["forwardAuth"]["authResponseHeaders"]
    es = _one("external-secret.yaml", "ExternalSecret", "healthchecks")
    keys = {d["secretKey"]: d["remoteRef"]["key"] for d in es["spec"]["data"]}
    assert keys["SECRET_KEY"] == "healthchecks-secret-key"
    assert keys["DB_PASSWORD"] == "healthchecks-db-password"
    for k in ("SECRET_KEY", "DB_PASSWORD", "PING_KEY", "PASSWORD"):
        assert k not in env, f"{k} is a secret and must not be in the ConfigMap"
    tf = (ROOT / "platform/oci/healthchecks.tf").read_text()
    for name in ("healthchecks-secret-key", "healthchecks-db-password", "healthchecks-ping-key"):
        assert f'"{name}"' in tf, f"{name} is not generated by platform/oci/healthchecks.tf"


def test_the_mac_and_the_server_share_one_ping_key():
    es = _one("external-secret.yaml", "ExternalSecret", "healthchecks")
    keys = {d["secretKey"]: d["remoteRef"]["key"] for d in es["spec"]["data"]}
    assert keys["PING_KEY"] == "healthchecks-ping-key"
    enrol = (ROOT / "bin/idp-hc-enroll").read_text()
    assert "healthchecks-ping-key" in enrol and ".estate/healthchecks" in enrol and "/ping_key" in enrol
    assert "/ping" in enrol and "/base" in enrol


def test_every_container_passes_the_restricted_profile():
    ns = _one("namespace.yaml", "Namespace", "healthchecks")
    assert ns["metadata"]["labels"]["pod-security.kubernetes.io/enforce"] == "restricted"
    assert ns["metadata"]["labels"]["idp.estate/edge-attach"] == "true"
    specs = [_one("healthchecks.yaml", "Deployment", "healthchecks")["spec"]["template"]["spec"],
             _one("postgres.yaml", "StatefulSet", "healthchecks-db")["spec"]["template"]["spec"]]
    for spec in specs:
        assert spec["securityContext"]["runAsNonRoot"] is True
        assert isinstance(spec["securityContext"]["runAsUser"], int) and spec["securityContext"]["runAsUser"] > 0
        assert spec["securityContext"]["seccompProfile"] == {"type": "RuntimeDefault"}
        assert spec["automountServiceAccountToken"] is False
        for c in spec.get("initContainers", []) + spec["containers"]:
            sc = c["securityContext"]
            assert sc["allowPrivilegeEscalation"] is False and sc["readOnlyRootFilesystem"] is True
            assert sc["capabilities"] == {"drop": ["ALL"]}
            assert "optional" not in yaml.safe_dump(c)


def test_flux_row_waits_on_the_deployment_after_the_front_door():
    docs = [d for d in yaml.safe_load_all((ROOT / "clusters/oke/platform.yaml").read_text()) if d]
    ks = next(d for d in docs if d["kind"] == "Kustomization" and d["metadata"]["name"] == "healthchecks")
    assert {d["name"] for d in ks["spec"]["dependsOn"]} >= {"identity", "secret-store"}
    assert ks["spec"]["wait"] is True and ks["spec"]["interval"] == "10m"
    assert ks["spec"]["healthChecks"] == [{"apiVersion": "apps/v1", "kind": "Deployment",
                                          "name": "healthchecks", "namespace": "healthchecks"}]
    assert {s["name"] for s in ks["spec"]["postBuild"]["substituteFrom"]} == {"estate-config"}
    grant = next(d for d in yaml.safe_load_all((ROOT / "platform/identity/httproute.yaml").read_text())
                 if d and d.get("kind") == "ReferenceGrant")
    assert "healthchecks" in {f["namespace"] for f in grant["spec"]["from"]}
