"""Founder, 2026-09 (directive in the portal work): "claude directives are polluting the
catalogue and are mostly noise; they should have a lesser section away from the rest."

The catalogue (catalog/catalog-info.yaml) is GENERATED by bin/catalog-gen from the estate
inventory (~/.estate/state/inventory.json); it is never hand-edited. Measured on the live
inventory of 303 ledger rows: 293 live under ~/.claude and most are per-session /
per-worktree / per-project scratch (a directives/*.jsonl per worktree, a
state/prompt-ledger/<session> per claude session, .claude/jobs/*/timeline.jsonl, and .wt-*
shadow copies of boards). Those were rendering as first-class members of
system:default/product-claude - which became the single largest "product" in the catalogue
(240 members), ahead of any real product - so .claude showed as the estate's #1 "product".

This file grades the fix "proved both ways", the estate's own test discipline:

  1. GOOD (this directive is obeyed): a per-session/per-worktree .claude ledger that
     bin/catalog-gen classifies as ephemeral is set apart - it lands on the dedicated
     system:default/estate-internals System with the `estate-internal` tag, not on any
     product System - while a durable op board (a real file the estate reads, e.g.
     ~/.claude/state/hook-outcomes.jsonl) and an estate repo board (.estate/**,
     crew-issues) keep their first-class place, and nothing is ever dropped.
  2. BAD (copy fails): if the ephemeral classifier were to stop applying, or if it wrongly
     demoted a durable board, the assertions below fail. The fixture inventory models all
     three shapes so the guard is sensitive, not vacuous.

Rung 2 properties (repeatable over one inventory) rather than prose: the generated file is
also required byte-identical across two runs by bin/idp-ci (idempotency) and reference-clean
by bin/catalog-refcheck, both run in CI over this same fixture.
"""

# ruff: noqa: S101, S603
# subprocess is deliberate: the gate is the produced catalogue, not a unit-test seam.

import os
import subprocess
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
MADIR = "tests/fixtures/inventory.json"
FIX = ROOT / MADIR
INTERNALS = "estate-internals"
INTERNALS_REF = f"system:default/{INTERNALS}"
EPHEMERAL_IDS = {
    "claude/directives/-Users-chidionyema-dev-code-idp-board",  # per-project directives log
    "claude/state/prompt-ledger/dev",  # per-session prompt ledger
}
DURABLE_IDS = {
    "claude/state/hook-outcomes",  # durable op board the estate reads (openReds/guards)
    "estate/knowledge/board/estate-board",  # estate repo board of record
    "ledger.sqlite",  # a ledger inside a tracked repo (fixture: shared name)
}


@pytest.fixture(scope="module")
def generated(tmp_path_factory) -> dict[str, dict]:
    """Run bin/catalog-gen over the fixture inventory exactly as bin/idp-ci does."""
    out = tmp_path_factory.mktemp("estate-internals") / "out"
    out.mkdir()
    p = subprocess.run(
        [str(ROOT / "bin" / "catalog-gen")],
        env={
            **os.environ,
            "INV": str(FIX),
            "OUT": str(out),
            "ESTATE_ENV": "dev",
            "CATALOG_GEN_ROOT": str(ROOT),
            "CATALOG_GEN_PROBE": "0",
        },
        capture_output=True,
        text=True,
    )
    assert p.returncode == 0, p.stderr
    docs = [d for d in yaml.safe_load_all((out / "catalog-info.yaml").read_text()) if d]
    return {
        "by_name": {d["metadata"]["name"]: d for d in docs},
        "internals_system": next(
            (
                d
                for d in docs
                if d.get("kind") == "System" and d["metadata"]["name"] == INTERNALS
            ),
            None,
        ),
    }


EPHEMERAL_IDENTS = {
    # suffix of estate/path that marks each ephemeral fixture ledger
    "/.claude/directives/": "-Users-chidionyema-dev-code-idp-board.jsonl",
    "/.claude/state/prompt-ledger/": "state/prompt-ledger/dev.jsonl",
}
DURABLE_IDENTS = {
    "claude/state/hook-outcomes": "/.claude/state/hook-outcomes.jsonl",
    "estate/knowledge/board/estate-board": "/.estate/knowledge/board/estate-board.jsonl",
    "ledger.sqlite": "ledger.sqlite",  # a ledger inside a tracked repo (fixture)
}


def _doc_for_path(generated: dict, needle: str) -> dict:
    """The ledger document whose estate/path (unhomed to ~/...) or name ends with `needle`.
    Matches on the real produced shape (unhomed ~/... path), not on an invented slug, so the
    guard stays correct however slugging or collision suffixes evolve."""
    for d in generated["by_name"].values():
        p = (
            d.get("metadata", {}).get("annotations", {}).get("estate/path")
            or d["metadata"]["name"]
        )
        if p.endswith(needle):
            return d
    raise AssertionError(f"no fixture ledger matching path suffix {needle!r}")


def test_ephemeral_claude_ledgers_are_set_apart_in_a_lesser_system(generated):
    """Directive: per-session/per-worktree .claude noise is NOT a product member. Each
    ephemeral fixture ledger lands on system:default/estate-internals with the estate-internal
    tag, not on product-claude/estate, and is still present (set apart, never deleted)."""
    for dirsuffix, filename in sorted(EPHEMERAL_IDENTS.items()):
        doc = _doc_for_path(generated, filename)
        spec = doc.get("spec", {})
        assert spec.get("type") == "ledger"
        assert spec.get("system") == INTERNALS_REF, (
            f"{filename!r} under {dirsuffix}: ephemeral ledger must move to {INTERNALS_REF}, "
            f"got {spec.get('system')}"
        )
        assert "estate-internal" in doc.get("metadata", {}).get("tags", []), (
            f"{filename!r}: must carry the estate-internal tag so the portal can keep it apart"
        )


def test_the_lesser_system_is_defined_and_self_describing(generated):
    """A system ref that names no System would 404 on click (the empty-shell failure).
    The estate-internals System doc exists and says this is internal, not a product."""
    sysdoc = generated["internals_system"]
    assert sysdoc is not None, (
        f"{INTERNALS_REF} is referenced but no System doc defines it"
    )
    title = sysdoc["metadata"]["title"]
    assert "internal" in title.lower() or "record" in title.lower(), title
    assert "estate-internal" in sysdoc["metadata"].get("tags", [])
    assert sysdoc.get("spec", {}).get("system") is None  # a System, not a member


def test_durable_op_boards_stay_first_class_never_demoted(generated):
    """The other half of 'mostly noise': the honest records are NOT noise. A durable op board
    the estate reads (hook-outcomes), an estate repo board, and a ledger inside a tracked repo
    keep their first-class place inside the real estate/product grouping - never the lesser
    System, never the estate-internal tag, never dropped."""
    for label, filename in sorted(DURABLE_IDENTS.items()):
        doc = _doc_for_path(generated, filename)
        spec = doc.get("spec", {})
        assert spec.get("system") != INTERNALS_REF, (
            f"{label}: durable board wrongly demoted to {INTERNALS_REF}"
        )
        assert "estate-internal" not in doc.get("metadata", {}).get("tags", []), (
            f"{label}: durable board wrongly tagged estate-internal"
        )


def test_classifier_is_discriminating_not_blunt(generated):
    """The predicate must separate an ephemeral session log from a durable board of the SAME
    kind. The fixture pairs a durable hook-outcomes board against a per-session prompt-ledger
    and a per-project directives ledger: all three are 'ledger' kind yet only the two session
    ones may leave the product grouping. Proves the rule keys off the path, not the kind: every
    ledger fixture row is exactly classified, with demotion (estate-internals System) equal
    to the estate-internal tag equal to the fixture's ephemeral expectation."""
    ephemeral_filenames = list(EPHEMERAL_IDENTS.values())
    durable_filenames = list(DURABLE_IDENTS.values())
    assert not set(ephemeral_filenames) & set(durable_filenames), (
        "test collides an ephemeral and a durable fixture needle"
    )
    for d in generated["by_name"].values():
        if d.get("spec", {}).get("type") != "ledger":
            continue
        tagged = "estate-internal" in d.get("metadata", {}).get("tags", [])
        internals = d.get("spec", {}).get("system") == INTERNALS_REF
        p = (
            d.get("metadata", {}).get("annotations", {}).get("estate/path")
            or d["metadata"]["name"]
        )
        expect_ephemeral = any(p.endswith(v) for v in ephemeral_filenames)
        assert tagged == internals == expect_ephemeral, (
            f"{d['metadata']['name']}: ephemeral/demoted {tagged}/{internals} disagrees with "
            f"fixture expectation ephemeral={expect_ephemeral}"
        )
        _expect_durable = any(p.endswith(v) for v in durable_filenames)
        assert not (expect_ephemeral and _expect_durable), (
            f"ambiguous fixture: {d['metadata']['name']}"
        )
