"""crew#561, 2026-08-30: idp#935 (06:29Z) and idp#949 (06:45Z) both changed the mac-run script and
both landed on the cluster; otto-parity 33295694219, run after Flux's window, still printed the old
script's `cp: cannot create regular file '/tmp/mac-run.id_ed25519'`. gateway.yaml mounts the
ConfigMap at /usr/local/bin/mac-run with `subPath`, and Kubernetes never refreshes a subPath-mounted
ConfigMap in a running pod (kubernetes.io/docs/concepts/storage/volumes, configMap: "a container
using a ConfigMap as a subPath volume mount will not receive ConfigMap updates"). Two merged fixes
reached no pod, and nothing said so. The ConfigMap is now generated by kustomize from mac-run.sh
with a content hash in its name, so a change renames it, rewrites the Deployment's reference, and
rolls the pod. This file holds that shape: the generator, the file, the hash, and no literal
ConfigMap of that name left behind to shadow it.
"""

import pathlib
import subprocess

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
HERMES = ROOT / "platform" / "hermes-agent"


def _kustomization() -> dict:
    return yaml.safe_load((HERMES / "kustomization.yaml").read_text())


def test_mac_run_is_a_generated_configmap_with_its_name_hash():
    ks = _kustomization()
    gens = [
        g
        for g in ks.get("configMapGenerator", [])
        if g["name"] == "hermes-agent-mac-run"
    ]
    assert gens, (
        "hermes-agent-mac-run must come from configMapGenerator, never a literal ConfigMap"
    )
    assert gens[0]["files"] == ["mac-run=mac-run.sh"], gens[0]
    assert (HERMES / "mac-run.sh").read_text().startswith("#!/bin/bash")
    assert ks.get("generatorOptions", {}).get("disableNameSuffixHash") is not True
    assert not (HERMES / "mac-run.yaml").exists(), (
        "a literal ConfigMap next to the generator would shadow the hash"
    )


def test_the_rendered_deployment_references_the_hashed_name():
    p = subprocess.run(
        ["kubectl", "kustomize", str(HERMES)], capture_output=True, text=True
    )
    assert p.returncode == 0, p.stderr
    docs = [d for d in yaml.safe_load_all(p.stdout) if d]
    cms = [
        d["metadata"]["name"]
        for d in docs
        if d["kind"] == "ConfigMap"
        and d["metadata"]["name"].startswith("hermes-agent-mac-run")
    ]
    assert len(cms) == 1 and cms[0] != "hermes-agent-mac-run", cms
    gw = next(
        d
        for d in docs
        if d["kind"] == "Deployment" and d["metadata"]["name"] == "hermes-agent-gateway"
    )
    vol = next(
        v for v in gw["spec"]["template"]["spec"]["volumes"] if v["name"] == "mac-run"
    )
    assert vol["configMap"]["name"] == cms[0], vol
