"""The jobs page tells the truth about a dispatched job, including when there is nothing to tell.

WHY THESE CASES. On 2026-09-13 a session re-sent its whole history every turn -- 177,570 tokens per
call, 56 calls in six minutes, 83% of one key's budget -- because its turn never ended. The tool
that ends the turn (`dispatch_job`) deliberately cannot report an outcome, so the outcome has to be
readable somewhere that is not the conversation. That somewhere is this page, and a page that lies
is worse than no page: it would make an unfinished job look finished and an invisible one look
absent.

The three states are the point, and the third is the one that matters:
  finished            the log's last line carries an exit
  still running       there is output and no exit
  no output recorded  nothing was written at all

The third is not a cosmetic gap. A job that never started and a job that finished silently are the
same shape on disk, and calling either "finished" is how a silent failure passes for a success.

The page is also proved not to touch the estate's other catalogue: backstage/platform/catalog-info
.yaml is GENERATED by bin/catalog-platform from 107 documents, so writing a jobs list into it would
corrupt that generator's output and be overwritten by its next run. It has its own file.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GATE = REPO / "bin" / "idp-jobs-page"


def run(tmp_path: Path, ledger: Path, *extra: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [
            sys.executable,
            str(GATE),
            "--ledger",
            str(ledger),
            "--out",
            str(tmp_path / "jobs.catalog-info.yaml"),
            *extra,
        ],
        capture_output=True,
        text=True,
        cwd=tmp_path,
        check=False,
    )


def ledger(tmp_path: Path, rows: list[dict]) -> Path:
    p = tmp_path / "jobs.jsonl"
    p.write_text("\n".join(json.dumps(r) for r in rows) + "\n", encoding="utf-8")
    return p


def row(name: str, log: Path, **extra) -> dict:
    base = {
        "id": name,
        "task": f"task for {name}",
        "command": "true",
        "cwd": str(Path.cwd()),
        "at": "2026-09-13T08:00:00Z",
        "log": str(log),
    }
    base.update(extra)
    return base


def test_a_finished_job_renders_as_finished(tmp_path: Path) -> None:
    """A log whose last line carries an exit is read, not guessed at."""
    log = tmp_path / "done.log"
    log.write_text("7 passed in 0.14s\n", encoding="utf-8")
    # `run` writes the exit to <id>.exit, NOT to the log. This fixture mirrors that, because a
    # fixture that does not is a test of the fixture.
    log.with_suffix(".exit").write_text("0\n", encoding="utf-8")
    led = ledger(tmp_path, [row("done", log)])

    r = run(tmp_path, led)

    assert r.returncode == 0, r.stderr
    assert "1 job(s), 1 exited 0" in r.stdout
    out = (tmp_path / "jobs.catalog-info.yaml").read_text(encoding="utf-8")
    assert "dispatched-job" in out, (
        "the entity must carry the tag the catalogue query uses"
    )


def test_a_job_that_wrote_nothing_is_not_called_finished(tmp_path: Path) -> None:
    """THE CASE THAT MATTERS. No log is not success.

    A ledger row is written the moment a job is submitted, before anything runs. On 2026-09-13 the
    dispatcher passed its command wrong and every job died at `nohup` -- yet the ledger looked
    clean. The log is the only thing that knew. If this page reported 'finished' for a missing log,
    it would reproduce exactly the blindness that hid that defect.
    """
    led = ledger(tmp_path, [row("never-started", tmp_path / "absent.log")])

    r = run(tmp_path, led)

    assert r.returncode == 0, r.stderr
    out = (tmp_path / "jobs.catalog-info.yaml").read_text(encoding="utf-8")
    assert "no output recorded" in out
    assert "production" not in out, (
        "an unrecorded job must not read as a production-healthy one"
    )
    assert "0 exited 0" in r.stdout


def test_a_running_job_is_not_called_finished(tmp_path: Path) -> None:
    """Output with no exit is a job still in flight, and it says so."""
    log = tmp_path / "running.log"
    log.write_text("collecting ...\n", encoding="utf-8")
    led = ledger(tmp_path, [row("running", log)])

    r = run(tmp_path, led)

    assert r.returncode == 0, r.stderr
    out = (tmp_path / "jobs.catalog-info.yaml").read_text(encoding="utf-8")
    assert "still running" in out
    assert "0 exited 0" in r.stdout


def test_a_job_that_failed_is_reported_as_failed(tmp_path: Path) -> None:
    """A non-zero exit is the one state a person must never have to go looking for."""
    log = tmp_path / "broke.log"
    log.write_text("AssertionError: 3 != 4\n", encoding="utf-8")
    log.with_suffix(".exit").write_text("1\n", encoding="utf-8")
    led = ledger(tmp_path, [row("broke", log)])

    r = run(tmp_path, led)

    assert r.returncode == 0, r.stderr
    out = (tmp_path / "jobs.catalog-info.yaml").read_text(encoding="utf-8")
    assert "FAILED, exited 1" in out
    assert "production" not in out, (
        "a failed job must not read as a production-healthy one"
    )
    assert "1 exited 0" not in r.stdout


def test_check_fails_when_the_ledger_has_moved_on(tmp_path: Path) -> None:
    """--check is the gate: a page that no longer matches its ledger must fail, not warn."""
    log = tmp_path / "done.log"
    log.write_text("collected\n", encoding="utf-8")
    log.with_suffix(".exit").write_text("0\n", encoding="utf-8")
    led = ledger(tmp_path, [row("first", log)])

    assert run(tmp_path, led).returncode == 0
    assert run(tmp_path, led, "--check").returncode == 0, (
        "a fresh page must pass --check"
    )

    # A second job is dispatched. The page on disk no longer matches the ledger.
    led.write_text(
        "\n".join(json.dumps(r) for r in [row("first", log), row("second", log)])
        + "\n",
        encoding="utf-8",
    )
    r = run(tmp_path, led, "--check")
    assert r.returncode == 1, "a stale page must fail, not pass quietly"
    assert "FAIL" in r.stderr


def test_an_empty_ledger_is_zero_jobs_and_not_a_failure(tmp_path: Path) -> None:
    """No jobs yet is a true statement about the estate, not an error.

    It also has to be distinguishable from a broken reader, so the message says which one it is.
    """
    led = ledger(tmp_path, [])

    r = run(tmp_path, led)

    assert r.returncode == 0, r.stderr
    assert "0 jobs" in r.stdout
    assert "not because the reader is broken" in r.stdout


def test_the_page_never_writes_the_generated_platform_catalogue(tmp_path: Path) -> None:
    """Its own file, always -- proved by running it, not by reading it.

    backstage/platform/catalog-info.yaml is generated by bin/catalog-platform and holds 107 YAML
    documents. A List written into it would break that generator and be overwritten by its next
    run -- so the page must default to a path of its own.

    This test used to read bin/idp-jobs-page and assert the literal OUT= assignment appeared in
    the text. That is a prose pin (R76): it grades a sentence about the gate rather than the gate,
    so renaming the constant would fail it while a real regression -- the page writing into the
    generated catalogue through some other route -- would pass it. Here the page is RUN with no
    --out, and the generated catalogue is watched: the default target is whatever actually changes.
    """
    generated = REPO / "backstage" / "platform" / "catalog-info.yaml"
    assert generated.exists(), "the generated catalogue is gone; this test grades it"
    before = generated.read_bytes()
    mtime_before = generated.stat().st_mtime_ns

    log = tmp_path / "one.log"
    log.write_text("did the thing\n", encoding="utf-8")
    log.with_suffix(".exit").write_text("0\n", encoding="utf-8")
    led = ledger(tmp_path, [row("one", log)])

    # No --out: the default target is the thing under test, so it has to be the real one.
    result = subprocess.run(
        [sys.executable, str(GATE), "--ledger", str(led)],
        capture_output=True,
        text=True,
        cwd=str(REPO),
        timeout=120,
        check=False,
    )
    assert result.returncode == 0, (
        f"the page failed with no --out: rc={result.returncode}\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    assert generated.read_bytes() == before, (
        "the page wrote into backstage/platform/catalog-info.yaml, which bin/catalog-platform "
        "generates and overwrites; it must default to a file of its own"
    )
    assert generated.stat().st_mtime_ns == mtime_before, (
        "the generated catalogue was rewritten in place; the page owns its own file"
    )
    own = REPO / "backstage" / "platform" / "jobs.catalog-info.yaml"
    assert own.exists(), "the page wrote nowhere at all; it has no default target"
    assert "task for one" in own.read_text(encoding="utf-8"), (
        "the default target exists but does not carry the job that was in the ledger"
    )
