"""crew#584 CP-H: the register promised a staging namespace (features.yaml: staging, on for every
tier) and the dev-loop how-to told people to point a kubeconfig at a "staging cluster" that no
file in clusters/ creates -- the documented loop could not be run. Staging is a namespace on the
one cluster: platform/staging, a Flux row named after the feature switch, a quota equal to the
register's floor, and bin/idp-dev as the one way in."""

import json
import pathlib
import re

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _docs(rel):
    return [d for d in yaml.safe_load_all((ROOT / rel).read_text()) if d]


def _by_kind(docs, kind):
    return next(d for d in docs if d["kind"] == kind)


def test_staging_namespace_carries_the_dev_loop_label_and_nothing_else_does():
    ns = _by_kind(_docs("platform/staging/namespace.yaml"), "Namespace")
    assert ns["metadata"]["name"] == "staging"
    assert ns["metadata"]["labels"]["idp.platform/dev-loop"] == "allowed"
    others = []
    for p in ROOT.glob("platform/**/*.yaml"):
        if "staging" in p.parts or "idp.platform/dev-loop" not in p.read_text():
            continue
        try:
            docs = [d for d in yaml.safe_load_all(p.read_text()) if isinstance(d, dict)]
        except yaml.YAMLError:
            continue
        others += [
            f"{p}:{d['metadata']['name']}"
            for d in docs
            if d.get("kind") == "Namespace"
            and d["metadata"].get("labels", {}).get("idp.platform/dev-loop")
        ]
    assert others == [], f"a production namespace carries the dev-loop label: {others}"


def test_quota_is_the_cap_the_register_priced():
    reg = yaml.safe_load((ROOT / "platform/features/features.yaml").read_text())
    feat = next(f for f in reg["features"] if f["name"] == "staging")
    tier = next(t for t in feat["tiers"] if t["name"] == "namespace")
    assert tier.get("status") in (None, "on", "trial"), (
        "staging must be selectable now its switch exists"
    )
    assert tier["switches"] == ["staging"]
    assert "floor" not in tier, (
        "features.yaml:17 -- only a planned tier carries a floor; the quota is the cap"
    )
    # crew#839: the ceiling is no longer hand-written beside the namespace. Every namespace's
    # quota is generated by bin/idp-ns-fence-gen from platform/ns-fences/allowances.yaml, and
    # staging's deliberate numbers moved into that file's `overrides` block. The register still
    # has to match the ceiling; only the file it is read from moved.
    hard = _by_kind(_docs("platform/ns-fences/staging.yaml"), "ResourceQuota")["spec"][
        "hard"
    ]
    # the ceiling idp#846 landed (2026-08-29): cpu 1, memory 2 GiB, storage 2 GiB, no public door
    assert (
        hard["requests.cpu"],
        hard["requests.memory"],
        hard["requests.storage"],
        hard["services.loadbalancers"],
    ) == ("1", "2Gi", "2Gi", "0")


def test_flux_row_is_named_after_the_switch():
    rows = [
        d for d in _docs("clusters/oke/platform.yaml") if d["kind"] == "Kustomization"
    ]
    row = next(r for r in rows if r["metadata"]["name"] == "staging")
    assert row["spec"]["path"] == "./platform/staging"
    assert row["spec"]["prune"] is True and row["spec"]["wait"] is True
    listed = yaml.safe_load((ROOT / "platform/staging/kustomization.yaml").read_text())[
        "resources"
    ]
    assert listed == [
        "namespace.yaml"
    ]  # crew#839: the quota moved to platform/ns-fences


def test_idp_dev_runs_in_staging_over_idp_kube_and_never_steals():
    src = (ROOT / "bin/idp-dev").read_text()
    assert (ROOT / "bin/idp-dev").stat().st_mode & 0o111
    assert "NS=staging" in src and '"$IDP/bin/idp-kube"' in src
    assert "MIRRORD_TARGET_NAMESPACE" in src and ".mirrord/staging.json" in src
    assert "steal" not in src
    cfg = json.loads((ROOT / ".mirrord/staging.json").read_text())
    assert cfg["target"] == "targetless" and cfg["agent"]["namespace"] == "staging"
    assert (
        cfg["feature"]["fs"] == "local"
        and cfg["feature"]["network"]["incoming"] == "off"
    )
    for p in ROOT.glob(".mirrord/*.json"):
        assert "steal" not in p.read_text() and '"write"' not in p.read_text(), p


def test_nothing_still_names_a_staging_cluster():
    hits = []
    for rel in (
        "docs/how-to/test-against-the-cluster.md",
        "platform/edge/dev-loop-policy.yaml",
        "bin/idp-dev",
    ):
        for i, line in enumerate((ROOT / rel).read_text().splitlines(), 1):
            if re.search(r"staging cluster|idp-kube staging", line):
                hits.append(f"{rel}:{i}")
    assert hits == [], hits
