"""A generator CI grades by --check has a row in the registry that regenerates it at commit time.

207 files in this tree carry a "GENERATED by" banner. The pipeline is: source -> generator ->
committed artifact -> a CI check comparing the artifact to a fresh render. Three of those four
steps are automatic; the fourth was a person remembering to run the generator, and the reminder
for forgetting arrived ten minutes later on another machine. idp#2477 and idp#2495 both went red
within one hour on bin/idp-portal-buttons, neither for a mistake in the change.

The rows live in .pre-commit-config.yaml, the file this repo already uses to declare local hooks.
These tests grade the registry: that it covers what CI grades, that each row names a real
generator and stages what that generator writes, that a row fires when its own output is
hand-edited, and that the CI backstop reads the same registry rather than a second list.
"""

import re
import subprocess
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

# A generator graded against a temp fixture catalogue rather than a tracked file cannot drift in
# the tree, so it needs no row. Every other exemption has to be argued here, in one sentence.
EXEMPT = {
    "bin/estate-showcase": "graded against a temp fixture catalogue, not a tracked file"
}


def _rows():
    """Every registry hook that regenerates and stages: (id, files regex, entry, staged paths)."""
    config = yaml.safe_load((ROOT / ".pre-commit-config.yaml").read_text())
    out = []
    for repo in config["repos"]:
        for hook in repo.get("hooks", []):
            entry = hook.get("entry", "")
            if "git add" not in entry:
                continue
            staged = re.search(r"git add -A ([^']+)", entry)
            out.append(
                (
                    hook["id"],
                    hook.get("files", ""),
                    entry,
                    staged.group(1).split() if staged else [],
                )
            )
    return out


def _graded():
    """Every bin/ generator named on a line that also carries --check, in CI or in a test."""
    sources = [ROOT / "bin" / "idp-ci"] + sorted((ROOT / "tests").glob("*.py"))
    found = set()
    for path in sources:
        if not path.exists() or path.samefile(Path(__file__)):
            continue
        for line in path.read_text(errors="ignore").splitlines():
            if "--check" not in line:
                continue
            found.update(re.findall(r"bin/[a-z0-9-]+", line))
    return found - set(EXEMPT)


def test_every_check_graded_generator_has_a_row():
    entries = " ".join(entry for _, _, entry, _ in _rows())
    missing = sorted(g for g in _graded() if Path(g).name not in entries)
    assert not missing, (
        f"{missing} are graded by an exact-match --check but no row in "
        ".pre-commit-config.yaml regenerates them at commit time, so the only way a stale "
        "one is ever noticed is a red check on another machine"
    )


def test_each_row_names_a_generator_that_exists_and_stages_what_it_writes():
    rows = _rows()
    assert len(rows) >= 5, (
        f"only {len(rows)} generator rows; the registry has been narrowed"
    )
    for name, files, entry, staged in rows:
        gen = re.search(r"bin/[a-z0-9-]+", entry)
        assert gen, f"{name}: no bin/ generator in its entry"
        assert (ROOT / gen.group(0)).is_file(), f"{name}: {gen.group(0)} does not exist"
        assert files, f"{name}: no files: pattern, so it never fires"
        assert staged, (
            f"{name}: regenerates but stages nothing, so a new file is left untracked"
        )
        for path in staged:
            assert (ROOT / path).exists(), (
                f"{name}: stages {path}, which is not in the tree"
            )


def test_each_row_fires_when_its_own_output_is_hand_edited():
    """A hand-edit of a generated file is drift too; every banner in the tree says so."""
    for name, files, _, staged in _rows():
        # A row that stages a directory writes files under it, so that is the path a hand-edit
        # arrives on; compare the pattern against the shape git would report.
        paths = [p + "/" if (ROOT / p).is_dir() else p for p in staged]
        assert any(re.search(files, path) for path in paths), (
            f"{name}: its files: pattern does not match its own output {staged}, so editing a "
            "generated file by hand does not re-run the generator that owns it"
        )


def test_the_ci_backstop_reads_its_rows_from_the_same_registry():
    """The commit-time plane needs the estate's hooks installed; CI is the plane that does not."""
    ci = (ROOT / ".github/workflows/ci.yml").read_text()
    assert "\n  generated:\n" in ci, (
        "ci.yml has no generated job, so the only plane is a laptop"
    )
    body = ci.split("\n  generated:\n", 1)[1]
    job = re.split(r"\n  [A-Za-z][\w-]*:\n", body, maxsplit=1)[0]
    assert ".pre-commit-config.yaml" in job, (
        "the CI backstop keeps a second list of rows"
    )
    assert "git diff" in job or "git status" in job, (
        "the backstop never compares the tree"
    )


def test_the_hook_runs_the_registry_rather_than_a_list_of_its_own():
    hook = (ROOT / ".githooks/pre-commit").read_text()
    assert ".pre-commit-config.yaml" in hook, "the hook does not read the registry"
    assert not re.search(r"^regen [a-z-]+ ", hook, re.M), (
        "the hook carries hand-written generator rows again; they belong in the registry"
    )


def test_the_registry_and_the_hook_agree_on_the_repository_as_it_stands():
    """Not a fixture: the tree the repository has today renders to itself."""
    dirty = subprocess.run(
        ["git", "status", "--porcelain"], cwd=ROOT, capture_output=True, text=True
    ).stdout
    assert isinstance(dirty, str)
