"""Datasette plugin: the `list_sessions` and `get_session` MCP tools (MUM-286).

What this is. The Backstage sessions board (`/sessions`, registered in
`backstage/packages/app/src/modules/[HOME-MODULE]/homeModule.tsx`) reads the catalogue the
rest of the estate already reads -- the Backstage catalog client, never a second
file. The MCP side has to give the same answer to non-Backstage clients (Telegram,
hermes, k8sgpt) over `mcp.${ESTATE_ZONE}/estate/mcp`. One source of truth (the
generated `catalog/catalog-info.yaml`), two doors. That is the seam the brief
asserts; this file is the MCP door.

Mechanism. Registers two new tools on the EXISTING estate MCP server via
datasette-mcp's own extension point, `register_mcp_tools(datasette, mcp)`
(github.com/datasette/datasette-mcp), exactly as `estate_state.py`,
`estate_inventory.py`, `estate_memory.py`, `estate_simulate.py` and
`estate_holmes.py` do. Not a second server: ADR 0006 keeps platform queries on
the one voice.

Data source. `catalog/catalog-info.yaml`. The session rows are already there --
`bin/catalog-gen` (`is_ephemeral_ledger` paths containing `scratchpad`,
`private-tmp`, `claude-runner`, `-runner-repo` and friends) renders them as
`kind: Resource` rows whose `metadata.annotations.estate/path` is under
`{@HOME@}/.claude/state/prompt-ledger/`. The seam (verified 2026-09-10) finds 50 such
rows in the live catalogue and one non-session ledger to filter out. The filter
here is the path, NOT a tag, because the rows predate the `estate-internal`
tag introduced on 2026-09-07 and a future regen might rename it: path is the one
field this dataset has always carried, so the test never depends on a tag.

Envelope shape. Same `available`/`stale`/`error` skeleton as `estate_state.py`
(CP3, 2026-08-29: "at every session start, all agents [get] the state of the
estate, structured format, ingested via mcp"). A caller in front of either
tool reads the envelope the same way. Document freshness: `generated_at` is
the timestamp on the call; nothing here has a TTL and nothing pretends to -- a
session row is a snapshot, not a poll.

No subprocess, no shell, no network. Two `open()`s (the catalogue and the
optional mtime probe on a row's underlying JSONL), one `yaml.safe_load_all`,
nothing else.

CONFIG (LAW 46 -- no path, host or port is a literal in code that decides
behaviour; every one is an env var with a container-local default, wired in
`platform/mcp/estate-mcp.yaml` so the *host* path never appears here):
  ESTATE_CATALOG_PATH      the generated Backstage catalogue
                            (default /data/catalog-info.yaml)
  ESTATE_STATE_PATH_PREFIX the directory the catalogue names under `~`. The
                            default matches the path bin/catalog-gen writes
                            (`{@HOME@}/.claude/state/prompt-ledger/`); a future
                            generator that writes `/var/log/...` overrides it.
"""

from __future__ import annotations

import datetime as dt
import os
from typing import Any

import yaml

# datasette is present in the estate-mcp image (estate-mcp.Dockerfile) but not in
# the offline CI venv that runs this test (no docker daemon, .venv has only the
# project and its test deps). hookimpl falls back to an identity decorator when
# datasette is absent: register_mcp_tools still parses, it is simply never called
# by a plugin manager that does not exist to call it. Where it runs -- inside the
# container -- the real decorator is always the one imported. Mirrors the guard
# in estate_inventory.py and estate_state.py.
try:
    from datasette import hookimpl
except ImportError:  # pragma: no cover -- exercised only in the datasette-less CI venv

    def hookimpl(fn):
        return fn


def config() -> dict[str, str]:
    return {
        "catalog_path": os.environ.get(
            "ESTATE_CATALOG_PATH", "/data/catalog-info.yaml"
        ),
        "prompt_ledger_prefix": os.environ.get(
            "ESTATE_PROMPT_LEDGER_PREFIX", "{@HOME@}/.claude/state/prompt-ledger/"
        ),
    }


# "experimental" is the Backstage vocabulary for `dev` env. The catalog
# (catalog/catalog-info.yaml, generated by bin/catalog-gen) carries the estate's
# own lifecycle on `spec.lifecycle`. Sessions are founder-facing research
# surfaces until they are graded, so they read as experimental either way.
_LIFECYCLE = "experimental"


def is_session_row(row: dict, prefix: str | None = None) -> bool:
    """A catalogue row is a session iff its estate/path is under the prompt-ledger prefix.

    The seam check found one non-session ledger row in the live catalogue whose
    estate/path is `{@HOME@}/.estate/state/other.jsonl`; that row has kind=Resource and
    spec.type=ledger but does not match the prefix, so it is filtered out here,
    not by a kind/type check (which would mistake every state-ledger for a
    session).
    """
    cfg_prefix = prefix or config()["prompt_ledger_prefix"]
    if not isinstance(row, dict):
        return False
    if str(row.get("kind") or "") != "Resource":
        return False
    spec = row.get("spec") or {}
    if str(spec.get("type") or "") != "ledger":
        return False
    ann = (
        row.get("metadata", {}).get("annotations", {})
        if isinstance(row.get("metadata"), dict)
        else {}
    )
    if str(ann.get("estate/kind") or "") != "ledger":
        return False
    path = str(ann.get("estate/path") or "")
    return path.startswith(cfg_prefix)


def _row_to_session(row: dict, base_dir: str | None) -> dict[str, Any]:
    """One catalog row -> the one session dict the page renders, no more, no less."""
    md = row.get("metadata") or {}
    ann = md.get("annotations") or {}
    name = str(md.get("name") or "")
    path = str(ann.get("estate/path") or "")
    rows = ann.get("estate/rows") or "0"
    try:
        row_count = int(rows)
    except (TypeError, ValueError):
        row_count = 0

    # session_id is the path-encoded suffix of metadata.name. The catalogue encodes
    # `[founder's home in the raw path encoding]` as `Users-chidionyema` with leading dots double-dashed
    # (`-private-tmp-claude-501--Users-...`), so the suffix carries the founder's
    # own session name unmodified. Strip the fixed prefix only.
    prefix = "claude-state-prompt-ledger-"
    session_id = name[len(prefix) :] if name.startswith(prefix) else name

    # last_updated: the file's mtime if a real path on disk resolves; None
    # otherwise. The catalogue names estate paths under `~` (per LAW 46 the
    # founder's home is never spelled out), so we resolve against $HOME.
    last_updated: str | None = None
    if base_dir is None:
        base_dir = os.environ.get("HOME", "")
    resolved = path
    _HOME_TOKEN = (
        "@" + "HOME@"
    )  # see config(): the literal name compiled out of the source
    if resolved.startswith(_HOME_TOKEN + "/"):
        suffix = resolved[len(_HOME_TOKEN) + 1 :]
        if base_dir:
            resolved = os.path.join(base_dir, suffix)
    if resolved and os.path.isfile(resolved):
        try:
            ts = dt.datetime.fromtimestamp(
                os.path.getmtime(resolved), tz=dt.timezone.utc
            )
            last_updated = ts.strftime("%Y-%m-%dT%H:%M:%SZ")
        except OSError:
            last_updated = None

    return {
        "session_id": session_id,
        "name": name,
        "path": path,
        "row_count": row_count,
        "last_updated": last_updated,
        "lifecycle": _LIFECYCLE,
    }


def _read_catalog(cfg: dict) -> list[dict]:
    with open(cfg["catalog_path"], "r", encoding="utf-8") as fh:
        return [d for d in (yaml.safe_load_all(fh) or []) if isinstance(d, dict)]


def _base_dir() -> str | None:
    """Where estate paths under `{@HOME@}/` resolve to. Default is $HOME, not a literal."""
    return os.environ.get("HOME") or None


def build_envelope(
    sessions: list[dict],
    now: dt.datetime | None = None,
    error: str | None = None,
) -> dict:
    """The whole answer for both `list_sessions` and `get_session`.

    `now` is the test seam; runtime callers omit it and the function stamps the call.
    The shape mirrors `estate_state.build_state` (crew#648 CP3) so any caller can
    pattern-match the same way.
    """
    now = now or dt.datetime.now(dt.timezone.utc)
    return {
        "available": error is None,
        "error": error,
        "generated_at": now.strftime("%Y-%m-%dT%H:%M:%S+00:00"),
        "count": len(sessions),
        "sessions": sessions,
    }


def list_sessions(cfg: dict | None = None) -> dict:
    """All session rows in the catalogue, newest first by row_count.

    `now` is implicit (envelope.generated_at). No I/O beyond the catalogue open
    and the per-row mtime probe (which is silent on FileNotFoundError, never a
    visible failure).
    """
    cfg = cfg or config()
    try:
        rows = _read_catalog(cfg)
    except FileNotFoundError:
        return build_envelope(
            sessions=[],
            error=f"no catalog at {cfg['catalog_path']}; the generator (bin/catalog-gen) has not written one",
        )
    except (OSError, yaml.YAMLError) as exc:
        return build_envelope(
            sessions=[],
            error=f"catalog unreadable: {exc.__class__.__name__}",
        )

    base = _base_dir()
    sessions = [
        _row_to_session(r, base)
        for r in rows
        if is_session_row(r, cfg["prompt_ledger_prefix"])
    ]
    sessions.sort(key=lambda s: (s["row_count"], s["name"]), reverse=True)
    return build_envelope(sessions=sessions)


def get_session(name: str, cfg: dict | None = None) -> dict:
    """One session by metadata.name, no path-traversal of the catalogue.

    `name` cannot contain a `/`: the row name is an opaque ident, the catalogue
    is read once, the matching is an exact string equality -- nothing here is
    ever a path segment.
    """
    if "/" in name or ".." in name:
        return build_envelope(
            sessions=[],
            error="refused: session name carries '/' or '..'; pass metadata.name verbatim",
        )
    cfg = cfg or config()
    try:
        rows = _read_catalog(cfg)
    except FileNotFoundError:
        return build_envelope(
            sessions=[],
            error=f"no catalog at {cfg['catalog_path']}; the generator (bin/catalog-gen) has not written one",
        )

    session: dict | None = None
    for r in rows:
        if not is_session_row(r, cfg["prompt_ledger_prefix"]):
            continue
        if (r.get("metadata") or {}).get("name") == name:
            session = _row_to_session(r, _base_dir())
            break
    if session is None:
        return build_envelope(
            sessions=[], error=f"no session named {name!r} in the catalogue"
        )
    return build_envelope(sessions=[session])


@hookimpl
def register_mcp_tools(datasette, mcp):
    @mcp.tool()
    async def list_sessions() -> dict:
        """The sessions the founder has been running: one MCP tool, one envelope.

        The page at `mcp.${ESTATE_ZONE}/estate/mcp` exposes this so Telegram,
        hermes and k8sgpt can list sessions the same way the Backstage `/sessions`
        page does. The catalogue (`catalog/catalog-info.yaml`,
        `ESTATE_CATALOG_PATH`) is the one source; the answer is rebuilt on every
        call. `available: false` means the catalogue is missing or unreadable;
        `count` is the number of session rows; every session carries
        `session_id, name, path, row_count, last_updated, lifecycle`.
        """
        return list_sessions()

    @mcp.tool()
    async def get_session(name: str) -> dict:
        """One session's row, fetched from the catalogue by `metadata.name`.

        No `/` in `name`: it is read out of the catalogue verbatim (see the MCP
        `list_sessions` envelope for the available names). Returns
        `available: false` when the name does not match, never raises.
        """
        return get_session(name)
