import { abilitiesSentence, barSentence, parseAbilities, parseBar } from './showcaseDocs';

const page = `# Estate showcase

GENERATED by \`bin/estate-showcase\` from \`catalog/catalog-info.yaml\` (inventory taken 2026-09-03T06:13:32Z), \`STANDARDS.md\` and the science page.

## The bar

- Entities: **582 ELITE**, **19 GAP**, **13 BLIND** of 614
- Standards rows: **11 live**, **12 not yet** of 23
`;

const inventory = `# Otto capability inventory

| **LIVE** | On the door's live request path today. |

### Senses

- **Reads every Telegram message on one hardened door**, two replicas. LIVE. \`platform/otto-gateway/deployment.yaml:22\`, \`registration-reconciler.yaml:258\`.
- **Hears voice notes** on the pod. IN THE IMAGE. \`tools/voice_mode.py:1402\`.
- **Never learns your voiceprint.** BUILT. \`otto/surface/identity.py\`.

### Reach

- **Telegram**, LIVE. **Agent-to-agent protocol** on port 9900, enabled. \`plugins/platforms/a2a/adapter.py:338\`.
- A line with no status word and the word alive in it.
`;

describe('the bar', () => {
  it('reads the four entity numbers, the standards rows and when the inventory was taken', () => {
    expect(parseBar(page)).toEqual({
      takenAt: '2026-09-03T06:13:32Z',
      entities: { elite: 582, gap: 19, blind: 13, total: 614 },
      standards: { live: 11, notYet: 12, total: 23 },
    });
  });
  it('claims nothing from a page without the bar', () => {
    expect(parseBar('# Estate showcase\n\nnothing graded yet\n')).toBeUndefined();
  });
  it('says the numbers in one sentence', () => {
    expect(barSentence(parseBar(page)!)).toBe(
      '614 catalogued things: 582 elite, 19 with a gap, 13 blind. 11 of 23 standards rows are live.',
    );
  });
});

describe('what Otto does today', () => {
  it('keeps only the LIVE lines, under their heading, with the receipts after the status word', () => {
    expect(parseAbilities(inventory)).toEqual([
      {
        sense: 'Senses',
        text: 'Reads every Telegram message on one hardened door, two replicas',
        receipts: [
          'platform/otto-gateway/deployment.yaml:22',
          'registration-reconciler.yaml:258',
        ],
      },
      {
        sense: 'Reach',
        text: 'Telegram',
        receipts: ['plugins/platforms/a2a/adapter.py:338'],
      },
    ]);
  });
  it('counts the abilities and names the senses they span', () => {
    expect(abilitiesSentence(parseAbilities(inventory))).toBe(
      '2 abilities live on the door today, across senses, reach.',
    );
    expect(abilitiesSentence([])).toBe('No Otto ability is marked live yet.');
  });
});
