import {
  abilitiesSentence,
  barSentence,
  formatRemaining,
  parseAbilities,
  parseBar,
  parseHoldMs,
  parseProgression,
  progressionSentence,
} from './showcaseDocs';

const page = `# Estate showcase

GENERATED by \`bin/estate-showcase\` from \`catalog/catalog-info.yaml\` (inventory taken 2026-09-03T06:13:32Z), \`STANDARDS.md\` and the science page.

## The bar

- Entities: **582 ELITE**, **19 GAP**, **13 BLIND** of 614
- Standards rows: **11 live**, **12 not yet** of 23
`;

const inventory = `# Otto capability inventory

| **LIVE** | On the door's live request path today. |

### Senses

- **Reads every Telegram message on one hardened door**, two replicas. LIVE. \`platform/otto-gateway/deployment.yaml:22\`, \`registration-reconciler.yaml:258\`.
- **Hears voice notes** on the pod. IN THE IMAGE. \`tools/voice_mode.py:1402\`.
- **Never learns your voiceprint.** BUILT. \`otto/surface/identity.py\`.

### Reach

- **Telegram**, LIVE. **Agent-to-agent protocol** on port 9900, enabled. \`plugins/platforms/a2a/adapter.py:338\`.
- A line with no status word and the word alive in it.
`;

describe('the bar', () => {
  it('reads the four entity numbers, the standards rows and when the inventory was taken', () => {
    expect(parseBar(page)).toEqual({
      takenAt: '2026-09-03T06:13:32Z',
      entities: { elite: 582, gap: 19, blind: 13, total: 614 },
      standards: { live: 11, notYet: 12, total: 23 },
    });
  });
  it('claims nothing from a page without the bar', () => {
    expect(parseBar('# Estate showcase\n\nnothing graded yet\n')).toBeUndefined();
  });
  it('says the numbers in one sentence', () => {
    expect(barSentence(parseBar(page)!)).toBe(
      '614 catalogued things: 582 elite, 19 with a gap, 13 blind. 11 of 23 standards rows are live.',
    );
  });
});

describe('what Otto does today', () => {
  it('keeps only the LIVE lines, under their heading, with the receipts after the status word', () => {
    expect(parseAbilities(inventory)).toEqual([
      {
        sense: 'Senses',
        text: 'Reads every Telegram message on one hardened door, two replicas',
        receipts: [
          'platform/otto-gateway/deployment.yaml:22',
          'registration-reconciler.yaml:258',
        ],
      },
      {
        sense: 'Reach',
        text: 'Telegram',
        receipts: ['plugins/platforms/a2a/adapter.py:338'],
      },
    ]);
  });
  it('counts the abilities and names the senses they span', () => {
    expect(abilitiesSentence(parseAbilities(inventory))).toBe(
      '2 abilities live on the door today, across senses, reach.',
    );
    expect(abilitiesSentence([])).toBe('No Otto ability is marked live yet.');
  });
});

describe('the roadmap', () => {
  it('keeps BUILT and IN THE IMAGE rows, with the spec step the line names', () => {
    expect(parseProgression(inventory)).toEqual([
      {
        sense: 'Senses',
        text: 'Hears voice notes on the pod',
        status: 'IN THE IMAGE',
        stepNumber: null,
        receipts: ['tools/voice_mode.py:1402'],
      },
      {
        sense: 'Senses',
        text: 'Never learns your voiceprint',
        status: 'BUILT',
        stepNumber: null,
        receipts: ['otto/surface/identity.py'],
      },
    ]);
  });
  it('extracts a step number when the line says "Step N" or "spec step N"', () => {
    const md = `### Reach
- **Hears voice notes.** IN THE IMAGE. \`tools/x.py:1\`. Wired to the door at spec step 3.
- **Speaks back.** IN THE IMAGE. \`tools/y.py:1\`. Step 4.
- **One more.** BUILT. \`tools/z.py\`.
`;
    expect(parseProgression(md)).toEqual([
      {
        sense: 'Reach',
        text: 'Hears voice notes',
        status: 'IN THE IMAGE',
        stepNumber: 3,
        receipts: ['tools/x.py:1'],
      },
      {
        sense: 'Reach',
        text: 'Speaks back',
        status: 'IN THE IMAGE',
        stepNumber: 4,
        receipts: ['tools/y.py:1'],
      },
      {
        sense: 'Reach',
        text: 'One more',
        status: 'BUILT',
        stepNumber: null,
        receipts: ['tools/z.py'],
      },
    ]);
  });
  it('returns an empty array when the inventory has nothing to grade', () => {
    expect(parseProgression('# Empty\n\nnothing here\n')).toEqual([]);
  });
  it('says in one sentence how many rows are on the roadmap when none has a step', () => {
    // The shared fixture has two BUILT/IN-THE-IMAGE rows, neither pinned to a step.
    const rows = parseProgression(inventory);
    expect(progressionSentence(rows)).toBe(
      '2 rows on the roadmap, none pinned to a spec step yet.',
    );
    expect(progressionSentence([])).toBe('Nothing on the roadmap yet.');
  });
  it('spells the step range when the rows point to it', () => {
    const md = `### Reach
- **A.** IN THE IMAGE. \`x.py\`. Step 2.
- **B.** BUILT. \`y.py\`. Step 5.
`;
    expect(progressionSentence(parseProgression(md))).toBe(
      '2 rows are one spec step from live: step 2 to step 5.',
    );
  });
});

describe('the hold parser and the countdown text', () => {
  it('reads hours, minutes, seconds and refuses anything else', () => {
    expect(parseHoldMs('1h')).toBe(60 * 60 * 1000);
    expect(parseHoldMs('4h')).toBe(4 * 60 * 60 * 1000);
    expect(parseHoldMs('30m')).toBe(30 * 60 * 1000);
    expect(parseHoldMs('90s')).toBe(90 * 1000);
    expect(parseHoldMs('')).toBeUndefined();
    expect(parseHoldMs(undefined)).toBeUndefined();
    expect(parseHoldMs('1 hour')).toBeUndefined();
    expect(parseHoldMs('0h')).toBeUndefined();
  });
  it('says how long is left in plain English', () => {
    expect(formatRemaining(0)).toBe('gone');
    expect(formatRemaining(-5)).toBe('gone');
    expect(formatRemaining(45_000)).toBe('45 seconds left');
    expect(formatRemaining(1_000)).toBe('1 second left');
    expect(formatRemaining(60_000)).toBe('1 minute left');
    expect(formatRemaining(2 * 60_000)).toBe('2 minutes left');
  });
});
