Feature: CP6 voice steering on both pages
  crew#973 done-means: "tell the one on the left to stop" reaches the right session.
  Voice is routed by spatial intent, not by name, and both pages share the same router.

  Scenario: focus on a comet by saying "the one on the left"
    Given the user is on /fleetview/river
    And two comets "<sha-a>" and "<sha-b>" are visible
    And "<sha-a>" is rendered to the left of "<sha-b>"
    When the user says "focus the one on the left"
    Then comet "<sha-a>" receives focus
    And the receipt hologram opens for "<sha-a>"
    And "<sha-b>" is unaffected

  Scenario: address a session by spatial relation not by name
    Given the user is on /fleetview/river
    When the user says "tell the one on the left to stop"
    Then the spoken intent is parsed by spatial relations (left/right/centre)
    And the target session receives the steering signal
    And the routing does not require the user to know the sha or the PR number

  Scenario: a steering phrase reaches the right MCP tool, named by intent
    Given the user says "tell the one on the left to stop"
    When the voice router classifies the intent
    Then the intent is "halt_session"
    And the routed target is the comet nearest the spatial reference "left"
    And the steering call goes through the estate MCP server (ADR 0006)
    And no LLM in the routing chain invents a target session

  Scenario: an unresolvable spatial reference is BLIND, never a guessed target
    Given the user says "the one in the back left" and no comet matches
    When the voice router tries to resolve
    Then the response is "no comet in the back left" verbatim
    And no steering signal is sent

  Scenario: the same spatial phrase works on the Observatory
    Given the user is on /fleetview/planes
    And ring 1 has two visible stars
    When the user says "the one on the right"
    Then the rightmost star receives focus
    And the focus mechanism is the same router as the River (no second implementation)

  Scenario: the voice router never invents a session id
    Given a steering intent
    When the routing decision is made
    Then the target session id is selected from the live catalogue (deploy_journeys
    rows or jev_decisions rows), never generated by the LLM
    And the chosen id is logged with the spatial reference and intent for audit

  Scenario: voice steering is gated by the same quota as the human on Telegram
    Given the user has used 8 of their 10 voice steers today
    When the user issues a 9th and a 10th
    Then both are accepted
    When the user issues an 11th
    Then the response names the daily limit and refuses, never sends a partial signal
