apiVersion: v1
kind: Secret
metadata:
  name: receiver-token
  namespace: flux-system
stringData:
  token: 69e82dc9f4cb7548a3be44277b7bdd9a1249937c1f21992b72aa7a2b65f2fb83
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-receiver
  namespace: flux-system
spec:
  type: github
  events:
    - ping
    - push
  secretRef:
    name: receiver-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
