//! Property lock: hand-written sentence splitter agrees with the Python oracle
//! (prose_measure.sentences) sentence-for-sentence over crafted documents that stress
//! abbreviation guards, brackets, embedded quotes, digit/currency terminators and heavy
//! comma use. The expected texts were generated by the real Python and stored beside these
//! tests; a divergence here is a port defect, not a choice.

use serde_json::Value;

fn load() -> Value {
    serde_json::from_str(include_str!("fixtures/sentence_property_oracle.json"))
        .expect("sentence_property_oracle.json is valid JSON")
}

#[test]
fn sentence_split_matches_python_word_for_word() {
    let docs = load();
    let map = docs.as_object().expect("oracle root is an object");
    let mut checked = 0usize;
    for (name, doc) in map {
        let text = doc["text"].as_str().expect("text");
        let want: Vec<&str> = doc["s"]
            .as_array()
            .expect("s array")
            .iter()
            .filter_map(|v| v.as_str())
            .collect();
        let got = voice_gate::house_measure::split_sentences(text);
        assert_eq!(
            got.len(),
            want.len(),
            "[{name}] sentence COUNT differs: got {} want {}",
            got.len(),
            want.len()
        );
        for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            assert_eq!(
                g,
                w,
                "[{name}] sentence #{i} differs:\n  got {:?}\n  want {:?}",
                g,
                w
            );
        }
        checked += want.len();
    }
    assert!(checked >= 20, "expected a meaningful corpus, saw {checked}");
}
